version: 2

builds:
  - main: ./cmd/helm-s3
    binary: ./bin/helm-s3
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64

archives:
  - id: tar
    format: tar.gz
    files:
      - LICENSE
      - plugin.yaml
